### ISSUE TITLE
Rstudio server not running

### ISSUE THREAD

**Issue by angelovangel** [tradestatistics/rstudio-server-droplet#1]
Hi,
I may be missing something, but when I create a rstudio-server droplet it seems that R server is not running (and I can't connect to server_ip:8787). 
```
sudo rstudio-server restart

rsession: no process found
```

`sudo rstudio-server start` also does not seem to work...

**Comment by pachadotdev** [comment]
Hi
At the risk of asking something weird, let's say the server ip is
123.456.01.02, are you going to 123.456.01.02:8787 from the browser?

**Comment by angelovangel** [comment]
Yes,
from the browser (chrome and safari) I do it like this. I can connect through ssh without problems, made a new user with sudo rights etc.

**Comment by pachadotdev** [comment]
Let me check ubuntu lastest updates
Probably you need to explicitly open http access

**Comment by angelovangel** [comment]
In the meantime: 
ssh tunnelling works, direct access to the server ip not...

**Comment by angelovangel** [comment]
Solved! I tried with a different ISP and it works, I guess the previous ISP had blocked some IP addresses.

**Comment by pachadotdev** [comment]
:O
That's probably a (not so bad) security policy
In that case I'd link the ip to mysite.com and activate https (https
requires a domain)
