### ISSUE TITLE
Setup instructions giving errors

### ISSUE THREAD

**Issue by esimms999** [tradestatistics/rstudio-server-droplet#10]
![DO_instructions](https://user-images.githubusercontent.com/10915780/180870513-0e49e550-6cdd-4f24-ad03-738fa8a8b52c.jpg)

**Comment by esimms999** [comment]
Instructions
![vps_instructions](https://user-images.githubusercontent.com/10915780/181029696-cce9e696-2de2-4489-ab56-7e2f2485f584.jpg)
:

**Comment by esimms999** [comment]
Perhaps there is no longer a default user, named rstudio, created when the droplet is spun up?

As for the ssh command, I am unsure what it is supposed to do.

**Comment by pachadotdev** [comment]
thanks! I made the change, indeed there's no default user in current versions after the improved DO security policy
the ssh command allows port forwarding, which allows a tunneled and secure connection

**Comment by pachadotdev** [comment]
@esimms999 hi! these changes are now implemented in the new version, there was a delay on DO's side to review my changes, now it's ok
