### ISSUE TITLE
Problem access

### ISSUE THREAD

**Issue by arnyeinstein** [tradestatistics/rstudio-server-droplet#2]
Hi
I installed the rstudio-server droplet and proceeded as described. However, I can't sign. I can open the login page in my browser, but I get the message "Incorrect/invalid  username  or password.
I also tried to start the rstudio server in my console, but have the same problem as the one disscussed here.
Cheers
Renger

**Comment by pachadotdev** [comment]
Hi

Let's check:
1. Did you create a user account? Root won't work
2. Can you post a redacted log?

**Comment by arnyeinstein** [comment]
Solved. It was a problem with the user I added (don't know what exactly, but I added a new user and now all is fine. 
THanks

**Comment by pachadotdev** [comment]
:O can you please tell me more?!

**Comment by arnyeinstein** [comment]
Sorry, I switched for the moment to shinyapps.io
