### ISSUE TITLE
cannot allocate vector of size 79.5 mb

### ISSUE THREAD

**Issue by ispajic** [tradestatistics/rstudio-server-droplet#3]
Hi,

I'm using a for loop on my dataframes 

joined <- for(userId in names(pred_groups)) {
    merge.data.frame(df.rating, df.matrix, by="movieId")
}

df.matrix has 13k rows and df rating 10 mil. I'm getting the out of memory error, but the for loop should be avoiding memory deficits and I took tg 4 GB droplet.

**Comment by pachadotdev** [comment]
hi
it is not possible to check for memory allocation on each step without a reproducible example
probably you need to scale the droplet
