### ISSUE TITLE
Multiple versions of R in DO Marketplace app?

### ISSUE THREAD

**Issue by esimms999-gsk** [tradestatistics/rstudio-server-droplet#6]
Re-wording the issue in the hope I can clarify. :)

I need to use R 3.6.3 for some package development work. I would appreciate a hint as to the best/easiest way to set up a Droplet on Digital Ocean for this:

- create an Ubuntu Droplet and manually install R 3.6.3 and RStudio Server (community edition)
- make use of some option in the Digital Ocean Marketplace app for RStudio to specify which version(s) of R to install 
- try to figure out PAT/ssh and make use of the analogsea package

Thanks.

**Comment by pachadotdev** [comment]
Hi
The current image offers R 4.1. I could eventually offer more images with previous R images, but at the present time I don't have much free time to do that. My apologies.
One alternative would be that you create your own image and keep a snapshot of it.
