### ISSUE TITLE
Error "Unable to connect to service" upon login 

### ISSUE THREAD

**Issue by dgdi** [tradestatistics/rstudio-server-droplet#7]
Hi,
I have used this marketplace image several times in the past and it is very handy, thanks for your work. However, I am not able to make it work lately. Everything goes fine during the set-up, I can access the droplet console from the Access panel of DO and add a new user (with its password) as explained in the tutorial. Using the browser I can go to the address ipofthedroplet:8787 and the Rstudio login shows. However, when I log in I get the error message "Unable to connect to service". Have you got any hint about what might be the problem? 
Thanks

**Comment by pachadotdev** [comment]
> 

hi
I'll fix this next saturday, I got another email where users needed to log via ssh in the lastest version, and then the rstudio user has web access

**Comment by pachadotdev** [comment]
@dgdi Hi!
I couldn't reproduce this error. Can you please send me a log or something. It works fine here.
