### ISSUE TITLE
RStudio version and R graphics engine version 15

### ISSUE THREAD

**Issue by psolymos** [tradestatistics/rstudio-server-droplet#8]
Looks like the listed 2021.09.2+382 version of the RStudio server does not support the new R (4.2.0) graphics engine, see warning:

```
R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(shiny)
Warning message:
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```

As a result, RStudio saves plots as pdf.

**Comment by luop0812** [comment]
I got the same error when using RStudio Server 1.4.1743

**Comment by psolymos** [comment]
Update: I could resolve the issue with a more recent version as expected:

```bash
# install RStudio Server
wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2022.02.2-485-amd64.deb
gdebi --n rstudio-server-2022.02.2-485-amd64.deb
rm rstudio-server-2022.02.2-485-amd64.deb
```

**Comment by esimms999** [comment]
From RStudio Community, December 2021: https://community.rstudio.com/t/rstudio-not-compatible-with-r-graphics-engine-version-15/124456

Also, the notes for this marketplace droplet say that RStudio v 4.1.0 will be installed. But when I did it today, version 4.2.0 is being installed.


![Screenshot 2022-06-16 140832](https://user-images.githubusercontent.com/10915780/174148961-e3f48f6f-b0f9-42d5-8d65-1a7794548ecc.jpg)

**Comment by pachadotdev** [comment]
I'll update this and I'll get back to you.

**Comment by pachadotdev** [comment]
hi @esimms999 @psolymos 
the only blocker to update is this https://serverfault.com/questions/1103802/force-non-interactive-setup-on-debian-ubuntu

**Comment by psolymos** [comment]
Would upgrading to Ubuntu 22.04 help?

**Comment by pachadotdev** [comment]
@esimms999 @psolymos I found a way to update OpenSSH remotely, and I was able to update the image
now we have to wait for the approval and a new version will be available
![image](https://user-images.githubusercontent.com/10091065/178399215-1cd0d395-d183-496b-bb92-6734622af684.png)
