### ISSUE TITLE
Actual and documented version of R are different

### ISSUE THREAD

**Issue by esimms999** [tradestatistics/rstudio-server-droplet#9]
![R_ver_documented](https://user-images.githubusercontent.com/10915780/180866313-57095a07-df2d-49d9-a212-9ff487ba4880.jpg)
![R_ver_actual](https://user-images.githubusercontent.com/10915780/180866334-b780377b-6b90-4042-abd7-607dcae66774.jpg)

**Comment by pachadotdev** [comment]
noted! I changed it in the docs
